# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven
on:
  push:
    branches-ignore:
      - 'master'
      - 'release*'
      - 'develop*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
    - name: Build with Maven
      run: mvn -B package --file pom.xml
  test:
    name: Unit Test
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
    - name: Maven Verify
      run: mvn -B clean verify
  publish:
    name: Publish    
    runs-on: ubuntu-latest
  
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
    - name: Maven Install
      run: mvn -B clean install
    - name: Build Container Image
      run: |
        sudo apt-get install libxml2-utils
        VERSION=$(xmllint --xpath "//*[local-name()='project']/*[local-name()='version']/text()" pom.xml)
        docker build -t govindarajanv/calculator-api:$VERSION .
        docker build -t govindarajanv/calculator-api:latest .
        docker images
    - name: Test Image
      uses: addnab/docker-run-action@v1
      with:
          image: govindarajanv/calculator-api:latest
          options: -d --name calculator-api --rm -p 9090:8080 govindarajanv/calculator-api
          run: curl -s http://localhost:8080/addition/1/2/3
