# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
    - name: Build with Maven
      run: mvn -B compile --file pom.xml
  unit-test:
    name: Unit Test
    needs: [build]
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
    - name: Unit Test
      run: mvn -B clean verify
  contract-test:
    name: Contract Test
    needs: [build]
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
    - name: API Contract Testing
      run: |
        mvn clean install
        sudo apt-get install libxml2-utils
        #VERSION=$(mvn -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:execxml)
        VERSION=$(xmllint --xpath "//*[local-name()='project']/*[local-name()='version']/text()" pom.xml)
        java -jar target/calculator-api-$VERSION.jar &
        PID=$!
        sleep 20
        result=$(curl -s http://localhost:8080/addition/1/2/3 | jq .result)
        if [ $result -eq 6 ]; then
          echo "API Contract Testing is successful"
        else
          echo "API Contract Testing failed"
          exit 1
        fi
        kill -9 $PID > /dev/null
  publish:
    name: Publish    
    runs-on: ubuntu-latest
    needs: [unit-test,contract-test]   

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
    - name: Deploy to Github Package Registry
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        mkdir -p ~/.m2
        echo "<settings><servers><server><id>github</id><username>govindarajanv</username><password>${GITHUB_TOKEN}</password></server></servers></settings>" > ~/.m2/settings.xml
        mvn clean deploy
    - name: Build Container Image
      run: |
        sudo apt-get install libxml2-utils
        VERSION=$(xmllint --xpath "//*[local-name()='project']/*[local-name()='version']/text()" pom.xml)
        docker build -t govindarajanv/calculator-api:$VERSION .
        docker build -t govindarajanv/calculator-api:latest .
        docker images
    - name: Test Image
      run: |
        docker-compose up -d
        docker ps
        sleep 60
        docker ps
        result=$(docker inspect --format='{{json .State.Health}}' calculator| jq ."Status")
        if [ $result != "\"healthy\"" ]; then exit 1; fi        
    - name: Shut down the service
      run: docker-compose down
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
    - name: Publish the image
      run: |
        VERSION=$(xmllint --xpath "//*[local-name()='project']/*[local-name()='version']/text()" pom.xml)
        docker push govindarajanv/calculator-api:$VERSION 
        docker push govindarajanv/calculator-api:latest
  integration-test:
    name: API Integration Testing
    runs-on: ubuntu-latest
    needs: [publish]
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
    - name: API Contract Testing
      run: |
        echo "Integration Testing is Stubbed"
