# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven
on:
  push:
    branches-ignore:
      - 'master'
      - 'release*'
      - 'develop*'
      - 'feature*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
      - name: Check Out Repo 
        uses: actions/checkout@v2
 
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: API Contract Testing
        run: |
          mvn clean install
          sudo apt-get install libxml2-utils
          VERSION=$(xmllint --xpath "//*[local-name()='project']/*[local-name()='version']/text()" pom.xml)
          docker build -t govindarajanv/calculator-api:$VERSION .
          docker build -t govindarajanv/calculator-api:latest .
          docker images
          docker push govindarajanv/calculator-api:$VERSION 
          docker push govindarajanv/calculator-api:latest
  deploy:
    name: Depploy/Release to production
    runs-on: ubuntu-latest
    steps:
    - name: Check Out Repo 
      uses: actions/checkout@v2
 
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
    - name: Deploy to Heroku
      run: |
        sudo apt-get install libxml2-utils
        VERSION=$(xmllint --xpath "//*[local-name()='project']/*[local-name()='version']/text()" pom.xml)      
        mvn clean install
        docker build -t registry.heroku.com/calculator-java-maven-service/web:$VERSION --build-arg value=$VERSION . 
        docker push registry.heroku.com/calculator-java-maven-service/web:$VERSION
        docker build -t registry.heroku.com/calculator-java-maven-service/web:latest --build-arg value=$VERSION .
        docker push registry.heroku.com/calculator-java-maven-service/web:latest
        heroku container:rm web -a calculator-java-maven-service
        heroku container:release web -a calculator-java-maven-service
        result=$(curl -s https://calculator-java-maven-service.herokuapp.com/addition/1/2/3 | jq .result)
        if [ $result -eq 6 ]; then
          echo "Application is successfully deployed in production"
        else
          echo "Prod deployment failed"
          exit 1
        fi    
