# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven
on:
  push:
    branches-ignore:
      - 'master'
      - 'release*'
      - 'develop*'
      - 'feature*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
      - name: Check Out Repo 
        uses: actions/checkout@v2
 
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: API Contract Testing
        run: |
          mvn clean install
          sudo apt-get install libxml2-utils
          VERSION=$(xmllint --xpath "//*[local-name()='project']/*[local-name()='version']/text()" pom.xml)
          docker build -t govindarajanv/calculator-api:$VERSION .
          docker build -t govindarajanv/calculator-api:latest .
          docker images
          docker push govindarajanv/calculator-api:$VERSION 
          docker push govindarajanv/calculator-api:latest
      - name: Share artifacts
        uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: target/*
          retention-days: 5
  deploy:
    name: Deploy/Release to production
    runs-on: ubuntu-latest
    steps:
      - name: Download a single artifact
        uses: actions/download-artifact@v2
        with:
          name: my-artifact
          path: target/
      - name: Deploy to Heroku
      - name: Build, Push and Deploy to Heroku #set the whatever name you want to this step
        id: heroku
        uses: jctaveras/heroku-deploy@v1.0.0  # use the latest version of the action
        with:
          email: ${{ secrets.HEROKU_EMAIL }} # your heroku email
          api_key: ${{ secrets.HEROKU_API_KEY }} # your  heroku api key
          app_name: ${{ secrets.HEROKU_APP_NAME }} # you aplication name
          dockerfile_path: '.' # set the path to the folder wher the Dokerfile is located
          options: '--build-arg value=1.0.1-SNAPSHOT' # Docker Build Options
          formation: '' # Docker Dyno Formation. By default is web 
